spring.datasource.url=${SICC_DB_URL:jdbc:postgresql://localhost:5432/sicc}
spring.datasource.username=${SICC_DB_USERNAME:postgres}
spring.datasource.password=${SICC_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
