CREATE TABLE usuarios_internos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    login VARCHAR(80) NOT NULL UNIQUE,
    senha_hash VARCHAR(100) NOT NULL,
    perfil VARCHAR(40) NOT NULL,
    ativo BOOLEAN NOT NULL,
    senha_temporaria BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    ultimo_acesso_em TIMESTAMP
);

CREATE TABLE setores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla VARCHAR(30) NOT NULL UNIQUE,
    nome VARCHAR(150) NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE processos_administrativos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(60) NOT NULL UNIQUE,
    origem VARCHAR(150) NOT NULL,
    numero_projeto VARCHAR(80),
    status VARCHAR(40) NOT NULL,
    data_cadastro DATE NOT NULL,
    ativo BOOLEAN NOT NULL,
    responsavel_id BIGINT,
    CONSTRAINT fk_processo_responsavel FOREIGN KEY (responsavel_id) REFERENCES usuarios_internos (id)
);

CREATE TABLE instrumentos_contratuais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processo_id BIGINT NOT NULL UNIQUE,
    numero VARCHAR(60) NOT NULL,
    tipo VARCHAR(60) NOT NULL,
    objeto VARCHAR(1000) NOT NULL,
    descricao VARCHAR(2000),
    natureza VARCHAR(150) NOT NULL,
    coordenador VARCHAR(150) NOT NULL,
    participes VARCHAR(2000) NOT NULL,
    valor_atual NUMERIC(19,2) NOT NULL,
    vigencia_contratual_final DATE NOT NULL,
    vigencia_ted_final DATE,
    data_formalizacao DATE NOT NULL,
    CONSTRAINT fk_instrumento_processo FOREIGN KEY (processo_id) REFERENCES processos_administrativos (id),
    CONSTRAINT uk_instrumento_identidade UNIQUE (numero, tipo, processo_id)
);

CREATE TABLE movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contexto_tipo VARCHAR(30) NOT NULL,
    contexto_id BIGINT NOT NULL,
    data_movimentacao DATE NOT NULL,
    sequencia_diaria INTEGER NOT NULL,
    setor_destino_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    observacao VARCHAR(1000),
    inserido_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_movimentacao_setor FOREIGN KEY (setor_destino_id) REFERENCES setores (id),
    CONSTRAINT fk_movimentacao_autor FOREIGN KEY (autor_id) REFERENCES usuarios_internos (id),
    CONSTRAINT uk_movimentacao_ordem UNIQUE (contexto_tipo, contexto_id, data_movimentacao, sequencia_diaria)
);

CREATE TABLE notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destinatario_id BIGINT NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    chave_idempotencia VARCHAR(180) NOT NULL UNIQUE,
    mensagem VARCHAR(1000) NOT NULL,
    lida BOOLEAN NOT NULL,
    criada_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_notificacao_destinatario FOREIGN KEY (destinatario_id) REFERENCES usuarios_internos (id)
);

CREATE TABLE documentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proprietario_tipo VARCHAR(30) NOT NULL,
    proprietario_id BIGINT NOT NULL,
    categoria VARCHAR(40) NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    ativo BOOLEAN NOT NULL,
    criado_por_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_documento_criador FOREIGN KEY (criado_por_id) REFERENCES usuarios_internos (id)
);

CREATE TABLE versoes_documento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_id BIGINT NOT NULL,
    versao INTEGER NOT NULL,
    nome_arquivo VARCHAR(255) NOT NULL,
    tipo_mime VARCHAR(120) NOT NULL,
    tamanho BIGINT NOT NULL,
    checksum_sha256 VARCHAR(64) NOT NULL,
    chave_armazenamento VARCHAR(500) NOT NULL UNIQUE,
    criado_em TIMESTAMP NOT NULL,
    criado_por_id BIGINT NOT NULL,
    CONSTRAINT fk_versao_documento FOREIGN KEY (documento_id) REFERENCES documentos (id),
    CONSTRAINT fk_versao_criador FOREIGN KEY (criado_por_id) REFERENCES usuarios_internos (id),
    CONSTRAINT uk_documento_versao UNIQUE (documento_id, versao)
);

CREATE TABLE alteracoes_contratuais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrumento_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL,
    numero_oficial VARCHAR(80) NOT NULL,
    ordem_oficial INTEGER,
    data_efetivacao DATE,
    referencia_id BIGINT,
    operacao VARCHAR(30) NOT NULL,
    documento_assinado_id BIGINT,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_alteracao_instrumento FOREIGN KEY (instrumento_id) REFERENCES instrumentos_contratuais (id),
    CONSTRAINT fk_alteracao_referencia FOREIGN KEY (referencia_id) REFERENCES alteracoes_contratuais (id),
    CONSTRAINT fk_alteracao_documento FOREIGN KEY (documento_assinado_id) REFERENCES documentos (id),
    CONSTRAINT uk_alteracao_numero UNIQUE (instrumento_id, tipo, numero_oficial)
);

CREATE TABLE alteracoes_campos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alteracao_id BIGINT NOT NULL,
    campo VARCHAR(60) NOT NULL,
    valor_anterior VARCHAR(3000),
    valor_novo VARCHAR(3000),
    CONSTRAINT fk_campo_alteracao FOREIGN KEY (alteracao_id) REFERENCES alteracoes_contratuais (id),
    CONSTRAINT uk_alteracao_campo UNIQUE (alteracao_id, campo)
);

CREATE TABLE relatorios_gerados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(40) NOT NULL,
    formato VARCHAR(10) NOT NULL,
    filtros VARCHAR(2000),
    chave_armazenamento VARCHAR(500) NOT NULL,
    criado_por_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_relatorio_criador FOREIGN KEY (criado_por_id) REFERENCES usuarios_internos (id)
);

CREATE TABLE registros_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    acao VARCHAR(80) NOT NULL,
    entidade VARCHAR(80) NOT NULL,
    entidade_id BIGINT,
    sucesso BOOLEAN NOT NULL,
    detalhes VARCHAR(2000),
    ip_origem VARCHAR(80),
    criado_em TIMESTAMP NOT NULL,
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios_internos (id)
);

CREATE INDEX idx_processos_status ON processos_administrativos (status);
CREATE INDEX idx_movimentacoes_contexto ON movimentacoes (contexto_tipo, contexto_id, data_movimentacao, sequencia_diaria);
CREATE INDEX idx_notificacoes_destinatario ON notificacoes (destinatario_id, lida);
CREATE INDEX idx_auditoria_entidade ON registros_auditoria (entidade, entidade_id);
