CREATE TABLE tramitacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_movimentacao TIMESTAMP NOT NULL,
    setor VARCHAR(120) NOT NULL,
    responsavel VARCHAR(150) NOT NULL,
    acao_realizada VARCHAR(200) NOT NULL,
    observacao VARCHAR(1000),
    etapa VARCHAR(120) NOT NULL,
    status_anterior VARCHAR(60),
    status_novo VARCHAR(60) NOT NULL,
    processo_id BIGINT NOT NULL,
    responsavel_usuario_id BIGINT,
    CONSTRAINT fk_tramitacoes_processo
        FOREIGN KEY (processo_id) REFERENCES processos (id),
    CONSTRAINT fk_tramitacoes_responsavel_usuario
        FOREIGN KEY (responsavel_usuario_id) REFERENCES usuarios (id)
);
