CREATE TABLE documentos_anexos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_arquivo VARCHAR(255) NOT NULL,
    tipo_arquivo VARCHAR(120) NOT NULL,
    caminho_arquivo VARCHAR(500) NOT NULL,
    descricao VARCHAR(1000),
    versao INTEGER NOT NULL,
    data_upload TIMESTAMP NOT NULL,
    enviado_por_id BIGINT,
    ativo BOOLEAN NOT NULL,
    processo_id BIGINT NOT NULL,
    CONSTRAINT fk_documentos_processo
        FOREIGN KEY (processo_id) REFERENCES processos (id),
    CONSTRAINT fk_documentos_enviado_por
        FOREIGN KEY (enviado_por_id) REFERENCES usuarios (id)
);
