CREATE TABLE logs_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    usuario_id BIGINT,
    acao VARCHAR(120) NOT NULL,
    entidade_afetada VARCHAR(120) NOT NULL,
    id_entidade_afetada BIGINT NOT NULL,
    detalhes VARCHAR(1000) NOT NULL,
    ip_origem VARCHAR(80),
    CONSTRAINT fk_logs_auditoria_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);
